### ISSUE TITLE
Error when using sentiment analysis

### ISSUE THREAD

**Issue by DigitalSport** [yangyaofei/nlpir-python#28]
The error info is listed below:

   >>> st=sentiment.SentimentNew()
Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nlpir/native/sentiment.py", line 22, in __init__

    super().__init__(encode, lib_path, data_path, license_code)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nlpir/native/nlpir_base.py", line 132, in __init__

    self.lib_nlpir, self.lib_path = self.load_library(sys.platform)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nlpir/native/nlpir_base.py", line 224, in load_library

    lib_nlpir = ctypes.cdll.LoadLibrary(lib)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary

    return self._dlltype(name)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 348, in __init__

    self._handle = _dlopen(self._name, mode)

OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nlpir/lib/libSentimentNewdarwin.so, 6): no suitable image found.  Did find:

	/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nlpir/lib/libSentimentNewdarwin.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

	/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nlpir/lib/libSentimentNewdarwin.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x0

**Comment by yangyaofei** [comment]
Reproduce bug in newest version. 

It's a bug from https://github.com/NLPIR-team/NLPIR, reported and will update when update of upstream.

**Comment by yangyaofei** [comment]
fixed
